version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-kitra
    environment:
      MYSQL_ROOT_USER: root #will be stored in docker secrets when deploying production
      MYSQL_ROOT_PASSWORD: 123456 #will be stored in docker secrets when deploying production
      MYSQL_DATABASE: kitra #will be stored in docker secrets when deploying production
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: kitra-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-kitra
    environment:
      PMA_HOST: mysql-kitra
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
