version: '3.8'

services:
  mysql:
    image: mysql:latest # Or specify a version like mysql:8.0
    container_name: mysql-kitra
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: kitra
    ports:
      - "3306:3306" # Maps the container's MySQL port to your host
    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage for database files

  app:
    container_name: kitra-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: kitra
volumes:
  mysql_data:
